version: '3.8'
services:
  viewvly_dev_server:
    container_name: viewvly_dev_server
    ports:
      - "1337:80"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped